// ── Generate src/data/posters.js from assets/covers/*.jpg (inline base64, zero async loading) ──
const fs = require('fs');
const path = require('path');

const coversDir = path.join(__dirname, '..', 'assets', 'covers');
const outFile = path.join(__dirname, '..', 'src', 'data', 'posters.js');
const assetsFile = path.join(__dirname, '..', 'src', 'data', 'coverAssets.js');

const files = fs
  .readdirSync(coversDir)
  .filter((f) => /\.jpe?g$/i.test(f))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const entries = files.map((f) => {
  const b64 = fs.readFileSync(path.join(coversDir, f)).toString('base64');
  return `  'data:image/jpeg;base64,${b64}'`;
});

const rawKb = Math.round(
  files.reduce((s, f) => s + fs.statSync(path.join(coversDir, f)).size, 0) / 1024
);

const out = `// Auto-generated by scripts/gen_posters.js — do not edit by hand.
// ${files.length} covers inlined as base64 (${rawKb}KB raw) for synchronous display.
export const posters = [
${entries.join(',\n')},
];
`;

// Parallel list of the SAME covers as local bundled assets (Expo standard require),
// used as a fallback when the base64 poster fails to load (e.g. native decode issue).
// Order MUST match `posters` above (same numeric filename sort).
const imports = files
  .map((f, i) => `import cover${String(i).padStart(2, '0')} from '../../assets/covers/${f}';`)
  .join('\n');
const assetEntries = files.map((f, i) => `  cover${String(i).padStart(2, '0')},`).join('\n');
const assetsOut = `// Auto-generated by scripts/gen_posters.js — do not edit by hand.
// Local bundled assets (Expo standard require) — fallback for base64 posters.
// Order matches posters.js.
${imports}

export const coverAssets = [
${assetEntries}
];
`;

fs.writeFileSync(outFile, out);
fs.writeFileSync(assetsFile, assetsOut);
console.log(`Generated ${outFile}: ${files.length} posters`);
console.log(`Generated ${assetsFile}: ${files.length} local assets`);
