// ── Generate src/data/posters.js from assets/covers/*.jpg (inline base64, zero async loading) ──
const fs = require('fs');
const path = require('path');

const coversDir = path.join(__dirname, '..', 'assets', 'covers');
const outFile = path.join(__dirname, '..', 'src', 'data', 'posters.js');

const files = fs
  .readdirSync(coversDir)
  .filter((f) => /\.jpe?g$/i.test(f))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const entries = files.map((f) => {
  const b64 = fs.readFileSync(path.join(coversDir, f)).toString('base64');
  return `  'data:image/jpeg;base64,${b64}'`;
});

const out = `// Auto-generated by scripts/gen_posters.js — do not edit by hand.
// ${files.length} covers inlined as base64 (${Math.round((fs.readdirSync(coversDir).filter(f=>/\.jpe?g$/i.test(f)).reduce((s,f)=>s+fs.statSync(path.join(coversDir,f)).size,0))/1024)}KB raw) for synchronous display.
export const posters = [
${entries.join(',\n')},
];
`;

fs.writeFileSync(outFile, out);
console.log(`Generated ${outFile}: ${files.length} posters`);
