#!/usr/bin/env python3
"""Generate src/data/coversBase64.js with all covers inlined as base64 data URIs.

Inlines poster-01..30.jpg so images render on iOS without depending on Metro's
asset-bundling step (which EAS's iOS builds were failing to name correctly).
"""
import base64
import os

ROOT = os.path.dirname(os.path.abspath(__file__)) + '/..'
SRC_DIR = os.path.join(ROOT, 'assets', 'covers')
OUT = os.path.join(ROOT, 'src', 'data', 'coversBase64.js')

uris = []
for i in range(1, 31):
    p = os.path.join(SRC_DIR, f'poster-{i:02d}.jpg')
    with open(p, 'rb') as f:
        data = f.read()
    uris.append('data:image/jpeg;base64,' + base64.b64encode(data).decode())

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED by scripts/generate_covers_base64.py — do not edit manually.\n')
    f.write('export const COVER_DATA_URIS = [\n')
    for uri in uris:
        f.write(f"  '{uri}',\n")
    f.write('];\n')

kb = sum(len(u) for u in uris) / 1024
print(f'wrote {OUT}: {len(uris)} data URIs, {kb/1024:.2f}MB')
